# If your site is in 'https', then make sure your base url isn't written using 'http' otherwise your sitemap would
# contain http (as opposeed to https) URLs. This would affect Google indexing of your URLs.
baseURL: "https://hofbauer.tech/"
title: Lukas Hofbauer
copyright: "© [PaperMod Contributors](https://github.com/adityatelange/hugo-PaperMod/graphs/contributors)"
paginate: 5
theme: [PaperMod]

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true
mainsections: ["publications", "projects", "posts",]

minify:
  disableXML: true
  # minifyOutput: true

languages:
  en:
    languageName: "English"
    weight: 1
    taxonomies:
      category: categories
      tag: tags
      series: series
    menu:
      main:
        - name: Search
          url: search/
          weight: 10
        - name: Tags
          url: tags/
          weight: 10

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  description: "Theme PaperMod - https://github.com/adityatelange/hugo-PaperMod"
  author: Lukas Hofbauer

  defaultTheme: auto
  # disableThemeToggle: true
  ShowShareButtons: true
  ShowReadingTime: true
  # disableSpecial1stPost: true
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowRssButtonInSectionTermList: true
  ShowAllPagesInArchive: true
  ShowPageNums: true
  ShowToc: false

  profileMode:
    enabled: true
    title: About Me
    subtitle: 
      Hi there! I'm Lukas, a cs master's student at the University of Innsbruck.
      Striving to become a AI/ML reseracher.  
    imageUrl: "img/headshot.jpg"
    # imageWidth: 120
    # imageHeight: 120
    buttons:
      - name: Contact Me
        url: contact
      - name: Resume
        url: resume.pdf

  socialIcons:
    - name: github
      title: My Github Repo
      url: "https://github.com/itsferguson"
    - name: X
      title: Share PaperMod on X/Twitter
      url: "https://x.com/its_fernnn"
    - name: LinkedIn
      title: Share PaperMod on X/Twitter
      url: "https://www.linkedin.com/in/hofbauer-lukas/"


markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai

services:
  instagram:
    disableInlineCSS: true
  twitter:
    disableInlineCSS: true
