baseURL = 'https://example.org/'
languageCode = 'en-us'
theme = 'beautifulhugo'

[Params]
  mainSections = ["publications", "post"]
  logo = "img/avatar-icon.png" # Expecting square dimensions
  bigimg = [{src = "/img/background.jpg"}]
  favicon = "img/favicon.ico"
  dateFormat = "January 2, 2006"
  socialShare = true
  delayDisqus = true
  showRelatedPosts = true

[Params.author]
  name = "Lukas Hofbauer"
  job = "Computer Science Student"
  bio = "I'm a Computer Science student at the University of Innsbrck. I'm interested in all things tech, especially in the fields of web development, machine learning and computer vision."
  website = "hofbauer.tech"
  email = "lukashofbauer@hotmail.com"
  github = "itsferguson"
  resume = "resume/resume.pdf"
  linkedin = "hofbauer-lukas"

[[Params.author.education]]
    degree = "BSc Computer Science"
    university = "University of Innsbruck"
    year = "2023"

[[Params.author.education]]
    degree = "MSc Computer Science"
    university = "University of Innsbruck"
    year = "ongoing"

